### ISSUE TITLE
Right top corner

### ISSUE THREAD

**Issue by efirs** [enricobacis/vim-airline-clock#1]
It works great!
Except that every window has it, would it be possible to put it into right top corner in tabline?

**Comment by enricobacis** [comment]
Do you mean still using vim-airline but in the tabline?

**Comment by efirs** [comment]
Yes

**Comment by enricobacis** [comment]
It's a good idea but I don't know when I'll have the time to look into it. Feel free to submit a PR if you code it before I do 😉

**Comment by enricobacis** [comment]
Apparently adding sections in the tabline is not yet supported by vim-airline.
https://github.com/vim-airline/vim-airline/issues/1517
