### ISSUE TITLE
[bug] cannot work

### ISSUE THREAD

**Issue by Freed-Wu** [enricobacis/vim-airline-clock#12]
```vim
" $ uname -r
" 5.13.8-arch1-1
" $ has nvim
" ✓ nvim 0.5.0
" $ has python
" ✓ python 3.9.6
" $ vi test.vim
set runtimepath=$VIMRUNTIME
set runtimepath+=~/.local/share/nvim/repos/github.com/vim-airline/vim-airline
set runtimepath+=~/.local/share/nvim/repos/github.com/enricobacis/vim-airline-clock
" $ vi -u test.vim
```

![image](https://user-images.githubusercontent.com/32936898/129479821-f032ba91-71ce-4980-98c4-e63c5708e2b8.png)

I cannot see any clock.

**Comment by Freed-Wu** [comment]
However, it can work if I
```
  let g:airline_filetype_overrides = {
        \ 'startify': ['startify', '%{airline#extensions#clock#get()}'],
        \ }
```

**Comment by enricobacis** [comment]
I never assessed the compatibility with neovim and it looks like you have a heavily extended vim airline installation, so, something might not be cross compatible for reasons that are difficult to predict.

Good that you got that working in the end.

**Comment by Freed-Wu** [comment]
Thank you for your reply.

I found I must add
```vim
  call airline#add_statusline_func('airline#extensions#clock#apply')
```
to make it work.

Thanks.
