### ISSUE TITLE
fatal: repository 'https://github.com/vim-scripts/vim-airline-clock.git/' not found

### ISSUE THREAD

**Issue by Rodrigoplp** [enricobacis/vim-airline-clock#2]
Steps to reproduce:
1. Using Vungle, add Plugin 'vim-airline-clock' to .vimrc;
2. Save file (: w) and resource it (:so %);
3. Install plugins (:PluginInstall);
4. Notice there is an error. Press l to see error log.

**Comment by enricobacis** [comment]
Hi @Rodrigoplp,

The URL of the repository is not the one specified by your error:

    https://github.com/vim-scripts/vim-airline-clock

but

    https://github.com/enricobacis/vim-airline-clock

Since it's not hosted in the vim-scripts repository, you need to replace the following line in your Vundle configuration

    Plugin 'vim-airline-clock'

with

    Plugin 'enricobacis/vim-airline-clock'

Please re-open the issue if that was not the case.

**Comment by Rodrigoplp** [comment]
Perfect! Thank you, Enrico.
