### ISSUE TITLE
Breaks vim-auto-save

### ISSUE THREAD

**Issue by skewwhiffy** [enricobacis/vim-airline-clock#6]
Using minpac and nvim 0.3.4

Installation of clock in nvim stops `vim-scripts/vim-auto-save` from working.

**Comment by vasilakisfil** [comment]
@skewwhiffy doesn't break it for me, I don't use nvim though, just "classic" (g)vim.

**Comment by skewwhiffy** [comment]
I've changed my workflow to compensate for this (using Gnome and some customized keyboard shortcuts). Closing this because I don't have time to reproduce this.
