### ISSUE TITLE
Update time is repeating too often and freezing up vim functionality like esc from insert mode.

### ISSUE THREAD

**Issue by ManBearPigg** [enricobacis/vim-airline-clock#9]
Love the plugin, thanks for it.

An issue though, I noticed esc from insert mode was taking like 3 full seconds. I logged what was happening and traced it back to the following in this plugin:

```
let g:airline#extensions#clock#timer = timer_start(
    \ g:airline#extensions#clock#updatetime,
    \ 'airline#extensions#clock#timerfn',{'repeat':-1})
```
I'm not sure what `-1` means, besides update the clock a billion times per second. I'm currently playing around with different values to figure out if the units are seconds or milliseconds or what, but changing it got my escape key back. 

I logged inserting some text then escaping out of insert and my log said that the clock was consuming 8 seconds. Not sure where the other 5 seconds come from. Probably from updating every millisecond while I was inserting text I guess. Anyways, maybe the default value should be changed, if I'm not misunderstanding something.

**Comment by ManBearPigg** [comment]
Nevermind, I am responsible for this madness. I had my own updatetime setting in vim set low, and like you clearly wrote in the README, the default (-1) goes off of your defaulttime. My bad.

**Comment by enricobacis** [comment]
No worries and thanks for the reminder. Even I forgot what `-1` was when I was reading your comment!
